### ISSUE TITLE
It keeps crashing my game.

### ISSUE THREAD

**Issue by X2GOLD** [kkllffaa/meteor-utils#19]
This is what the error code is
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: meteordevelopment/meteorclient/systems/commands/Command
Please someone help

**Comment by cqb13** [comment]
the way commands work was changed a bit, I fixed the issue but not sure when or if the owner will merge it.
But here is a working version, if you want one.
https://github.com/cqb13/meteor-utils/releases/tag/0.1

**Comment by L1ghtn1ng-cmd** [comment]
re upload? link doesn't exist
