### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by kykyruza134** [kkllffaa/meteor-utils#25]
when you click Dupe All, phantom things appear that disappear almost immediately.
I haven't figured out how to use OpenAnarchyAutoDupe yet
https://drive.google.com/file/d/1CHYZ60yCHI2KHg6GH9g4BXa3JsHsHfQR/view?usp=sharing

**Comment by kkllffaa** [comment]
Shulker dupe was pathed in 1.19+ and OpenAnarchyAutoDupe was module for duping on now closed openanarchy server.
I will remove them and other outdated modules when i will have time to update this mod.
