### ISSUE TITLE
Add the shulker dupe as a module

### ISSUE THREAD

**Issue by The-Nyla** [kkllffaa/meteor-utils#4]
I know I can "Just use the mod", however the mod is completely broken on any recent version of the fabric API/fabric, and therefore it's impossible to use the latest versions of meteor with the shulker dupe. it would also just be a useful addition

**Comment by kkllffaa** [comment]
https://github.com/GuiltsMC/1.18-Shulker-Dupe-Mod
this one?

**Comment by The-Nyla** [comment]
I actually meant this one: https://github.com/Coderx-Gamer/shulker-dupe

but they both do the same thing and neither work with newer fabric/fabric API versions

**Comment by kkllffaa** [comment]
i added it in new release
